name: Prerelease

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        archetect-options:
          - '-s github -s cdn -s angular -a repository-name=app-web-angular'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - uses: scaffoldly/archetect-render-action@v1
        with:
          source: '.'
          destination: '${{ runner.temp }}/rendered'
          options: '${{ matrix.archetect-options }}'
          commit: 'false'
      - run: yarn
        working-directory: '${{ runner.temp }}/rendered'
  prerelease:
    needs: render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: scaffoldly/bump-version-action@v1
        with:
          action: prerelease
          version-file: sly.json
          repo-token: ${{ secrets.GITHUB_TOKEN }}
